apiVersion: v1
kind: Service
metadata:
  labels:
    service: mysql
  name: mysql
  {{- if .Values.topologyAwareServices }}
  annotations:
    service.kubernetes.io/topology-mode: "Auto"
  {{- end }}
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    service: mysql
