apiVersion: v1
data:
  default_user.conf: ZGVmYXVsdF91c2VyID0gdXNlcl9yb2JvdC1zaG9wCmRlZmF1bHRfcGFzcyA9IHVzZXJfcm9ib3Qtc2hvcAo=
  host: dmF1bHQtZGVmYXVsdC11c2VyLmRlZmF1bHQuc3Zj
  password: dXNlcl9yb2JvdC1zaG9w
  port: NTY3Mg==
  provider: cmFiYml0bXE=
  type: cmFiYml0bXE=
  username: dXNlcl9yb2JvdC1zaG9w
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  labels:
    service: rabbitmq
spec:
  replicas: {{ default 1 .Values.defaultReplicas }}
  {{- with .Values.rabbitmq.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  override:
    statefulSet:
      spec:
        template:
          spec:
            {{- if .Values.rootOnlyFilesystem }}
            containers: []
            initContainers: []
            securityContext: {}
            {{- else }}
            containers: []
            {{- end }}
            {{- with .Values.rabbitmq.nodeSelector }}
            nodeSelector:
              {{- toYaml . | nindent 14 }}
            {{- end }}
  {{- with .Values.rabbitmq.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  secretBackend:
    externalSecret:
      name: rabbitmq-secret
