apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis
  name: redis
spec:
  {{- if .Values.topologyAwareServices }}
  trafficDistribution: PreferClose
  {{- end }}
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    service: redis
